### ISSUE TITLE
Release 0.5 on pypi.python.org

### ISSUE THREAD

**Issue by earlchew** [sassoftware/python-keyutils#25]
The new APIs are not available on the current release 0.4.

**Comment by mibanescu** [comment]
Done. Thank you for all your work. I should add you to the AUTHORS file. How would you like your name and email to show up?

**Comment by earlchew** [comment]
Thanks. I enjoyed the collaboration.

**Comment by Ambrevar** [comment]
What about a git tag? Or a github release?

**Comment by mibanescu** [comment]
Sorry, it was already tagged, but I had forgotten to push the tags. Done now.

**Comment by Ambrevar** [comment]
ChangeLog is out of date.
For a small project, you might consider leaving it out and rely on git logs instead.
