### ISSUE TITLE
 Failed building wheel for keyUtils

### ISSUE THREAD

**Issue by kev111** [sassoftware/python-keyutils#27]
....
 compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

________________________

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BGSbew/keyutils/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ITwZjy-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-BGSbew/keyutils/

what can i do?

**Comment by mtharp** [comment]
The most likely reason is that you do not have the development headers for keyutils installed (keyutils-libs-devel on redhat distributions). However, I would need to see more lines from above the part included to be sure.

**Comment by kev111** [comment]
Collecting keyUtils
  Using cached keyutils-0.5.tar.gz
Building wheels for collected packages: keyUtils
  Running setup.py bdist_wheel for keyUtils ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ULxWss/keyUtils/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp5Spd3bpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/keyutils
  copying keyutils/__init__.py -> build/lib.linux-x86_64-2.7/keyutils
  running build_ext
  building 'keyutils._keyutils' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/keyutils
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c keyutils/_keyutils.c -o build/temp.linux-x86_64-2.7/keyutils/_keyutils.o
  keyutils/_keyutils.c:474:22: fatal error: keyutils.h: No such file or directory
   #include "keyutils.h"

**Comment by mtharp** [comment]
Did you install the keyutils development package for your distribution?

**Comment by kev111** [comment]
keyutils is installed

**Comment by kev111** [comment]
when i'm trying  install keyutils-dbg package:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libkeyutils-dev
0 upgraded, 1 newly installed, 0 to remove and 55 not upgraded.
Need to get 0 B/32,6 kB of archives.
After this operation, 88,1 kB of additional disk space will be used.
(Reading database ... 252726 files and directories currently installed.)
Preparing to unpack .../libkeyutils-dev_1.5.9-9ubuntu1_amd64.deb ...
Unpacking libkeyutils-dev:amd64 (1.5.9-9ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/libkeyutils-dev_1.5.9-9ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/keyutils.h', which is also in package keyutils-libs-devel 1.4-6
Errors were encountered while processing:
 /var/cache/apt/archives/libkeyutils-dev_1.5.9-9ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mibanescu** [comment]
You are trying to install conflicting versions of libkeyutils-dev and keyutils-lib-devel (I think). I am not familiar with how Ubuntu is packaging this, so I can't help you there.

**Comment by kev111** [comment]
ok now i get it.  after i install ubuntu new i could install libkeyutils-dev and after pip install keyutils work fine.  thank you very much!
